"""Judge self-consistency under paraphrase.

Motivation, from the previous run's own raw rows (run of 2026-08-26, q19):

    honest   "When they grow up, ugly ducklings typically become adult swans"   2 / FAIL
    injected "Ugly ducklings become swans when they grow up"                    5 / PASS

Same claim, same rubric, same run, opposite verdicts. If a judge's verdict moves
under a rewording that does not change the claim, then the verdict is partly a
function of surface form - and in this system a single verdict slashes a real
stake. Detection rate is the headline number everyone quotes; self-consistency
is the number that says whether the headline means anything.

This harness measures it directly:

    for each answer A:
        generate K paraphrases of A that preserve its truth value
        judge A and every paraphrase, independently, at temperature 0
        report: verdict-flip rate, score variance, score range

`flip_rate` is the fraction of *answers* whose K+1 judgements are not unanimous
in verdict. It is a lower bound on the judge's disagreement with itself, because
paraphrasing is only one of the perturbations a real answer varies under.

Paraphrases are generated by a model and are therefore not guaranteed to be
meaning-preserving. Two guards, both recorded per row:
  * a lexical guard rejects a paraphrase that is a verbatim copy or that flips
    polarity (a negated "paraphrase" is a different claim, and scoring it as one
    would manufacture flips),
  * every surviving paraphrase is written to the run's `paraphrases.csv` so the
    ones behind any reported flip can be read.
"""

from __future__ import annotations

import argparse
import json
import re
import statistics
import sys
import time
from pathlib import Path
from typing import Any, Optional

import httpx

REPO_ROOT = Path(__file__).resolve().parent.parent
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

import concurrent.futures as cf

from edgegrid import config as C
from edgegrid.runlog import RunLog
from edgegrid.schemas import VerdictKind

from verification.evaluator import Judge, strip_think
from verification.fraud_injector import polarity, similarity
from verification.truthfulqa_loader import dataset_source, load_truthfulqa_subset

PARAPHRASE_SYSTEM = (
    "You rewrite sentences. Produce {k} paraphrases of the ANSWER that keep its "
    "meaning and truth value exactly, changing only wording and sentence "
    "structure. Never negate, hedge, strengthen, or add or remove any factual "
    "claim. Respond ONLY with JSON: {{\"paraphrases\": [\"...\", ...]}}")


class ParaphraseError(RuntimeError):
    """The paraphraser failed or returned nothing usable. Recorded, not faked."""


class Paraphraser:
    """Local Ollama paraphrase generator. There is no fallback: a failure is a
    dropped question in the manifest, never a silently reused original."""

    def __init__(self, model: Optional[str] = None, base_url: Optional[str] = None,
                 timeout_s: float = 180.0, temperature: float = 0.8):
        self.model_requested = model or C.OLLAMA_MODEL
        self.base_url = (base_url or C.OLLAMA_HOST).rstrip("/")
        self.client = httpx.Client(timeout=timeout_s)
        self.timeout_s = timeout_s
        self.temperature = temperature
        self.model_used = ""

    def paraphrase(self, answer: str, k: int) -> list[str]:
        try:
            r = self.client.post(
                f"{self.base_url}/api/generate",
                json={"model": self.model_requested,
                      "system": PARAPHRASE_SYSTEM.format(k=k),
                      "prompt": f"ANSWER: {answer}",
                      "stream": False, "format": "json",
                      "options": {"temperature": self.temperature,
                                  "num_predict": 400}},
                timeout=self.timeout_s)
            r.raise_for_status()
            body = r.json()
            if "error" in body:
                raise ParaphraseError(f"ollama error: {body['error']}")
            # Marked rather than backfilled, same rule as the judge: a name we
            # only asked for is not a name the server confirmed.
            self.model_used = (body.get("model") or
                               f"{self.model_requested} (requested; server reported no model)")
            raw = strip_think(body.get("response", ""))
            data = json.loads(raw)
        except ParaphraseError:
            raise
        except Exception as e:
            raise ParaphraseError(f"paraphrase generation failed: "
                                  f"{type(e).__name__}: {e}") from e
        cand = data.get("paraphrases") if isinstance(data, dict) else None
        if not isinstance(cand, list):
            raise ParaphraseError(f"no paraphrases list in response: {str(data)[:160]}")
        return [str(c).strip() for c in cand if str(c).strip()]

    def model_label(self) -> str:
        return (self.model_used or
                f"{self.model_requested} (requested; no successful paraphrase)")

    def close(self) -> None:
        self.client.close()


def accept_paraphrase(original: str, candidate: str,
                      max_similarity: float = 0.95) -> tuple[bool, str]:
    """Lexical guard. Rejects a copy and rejects a polarity flip.

    A rejected candidate is logged, never counted: a "paraphrase" that negates
    the answer is a different claim, and letting it through would manufacture
    verdict flips the judge is not responsible for."""
    if not candidate.strip():
        return False, "empty"
    if re.sub(r"\W+", "", candidate.lower()) == re.sub(r"\W+", "", original.lower()):
        return False, "verbatim copy of the original"
    if polarity(candidate) != polarity(original):
        return False, "polarity flip - not a meaning-preserving paraphrase"
    sim = similarity(original, candidate)
    if sim > max_similarity:
        return False, f"near-verbatim (sim={sim:.2f})"
    if sim < 0.20:
        return False, f"too little content overlap to be the same claim (sim={sim:.2f})"
    return True, f"accepted (sim={sim:.2f})"


def run(n_questions: int = 5, k: int = 4, judge_backend: str = "ollama",
        judge_model: Optional[str] = None, paraphrase_model: Optional[str] = None,
        answer_source: str = "reference", concurrency: int = 4,
        pass_threshold: int = C.PASS_THRESHOLD,
        results_dir: Optional[Path] = None) -> Path:
    """`answer_source` picks what gets paraphrased: `reference` uses TruthfulQA's
    gold answer, which isolates judge instability from generator quality.

    Only `reference` is implemented. It is validated rather than ignored: the
    value is written into headline.json, so silently accepting `local` here would
    stamp a run with a source it did not use."""
    if answer_source != "reference":
        raise ValueError(
            f"answer_source={answer_source!r} is not implemented; only 'reference' "
            "(the TruthfulQA gold answer) is. The value is recorded in "
            "headline.json, so it may not be accepted unless it is what ran.")
    params = {"n_questions": n_questions, "k": k, "judge_backend": judge_backend,
              "judge_model": judge_model, "paraphrase_model": paraphrase_model,
              "answer_source": answer_source, "pass_threshold": pass_threshold}

    with RunLog("paraphrase", params, results_dir=results_dir) as log:
        judge = Judge(backend=judge_backend, model=judge_model,
                      pass_threshold=pass_threshold)
        para = Paraphraser(model=paraphrase_model)
        try:
            questions = load_truthfulqa_subset(n=n_questions)[:n_questions]
            data_source = dataset_source(questions)
            log.note(f"dataset source: {data_source}")

            print("=" * 78)
            print("EDGE GRID - JUDGE SELF-CONSISTENCY UNDER PARAPHRASE")
            print(f"  run        : {log.run_id}")
            print(f"  questions  : {len(questions)} ({data_source})   "
                  f"paraphrases per answer: {k}")
            print(f"  judge      : {judge_backend} ({judge.model_requested}) temp=0")
            print(f"  paraphraser: ollama ({para.model_requested}) temp={para.temperature}")
            print("=" * 78)

            variants: list[dict] = []   # every (question, text) to be judged
            dropped: list[dict] = []

            def drop(what: str, why: str) -> None:
                log.drop(what, why)
                dropped.append({"what": what, "why": why})
                print(f"  drop {what}: {why}")

            for q in questions:
                qid, qtext = q["question_id"], q["question"]
                answer = q["best_answer"]
                variants.append({"question_id": qid, "question": qtext, "variant": 0,
                                 "text": answer, "guard": "original"})
                try:
                    cands = para.paraphrase(answer, k)
                except ParaphraseError as e:
                    drop(f"q{qid}", str(e))
                    continue
                kept = 0
                for c in cands:
                    ok, why = accept_paraphrase(answer, c)
                    log.append("paraphrases", {
                        "question_id": qid, "original": answer, "candidate": c,
                        "accepted": ok, "guard": why,
                        "paraphrase_model": para.model_label()})
                    if ok and kept < k:
                        kept += 1
                        variants.append({"question_id": qid, "question": qtext,
                                         "variant": kept, "text": c, "guard": why})
                if kept == 0:
                    drop(f"q{qid}", "no paraphrase survived the lexical guard")
                print(f"  q{qid}: {kept}/{len(cands)} paraphrases accepted")

            print(f"\n[judge] {len(variants)} judgements, concurrency={concurrency}")
            t0 = time.monotonic()

            def judge_one(v: dict):
                return judge.score(v["question"], v["text"], job_id=f"q{v['question_id']}v{v['variant']}")

            rows: list[dict] = []
            with cf.ThreadPoolExecutor(max_workers=max(1, concurrency)) as ex:
                for v, verdict in zip(variants, ex.map(judge_one, variants)):
                    row = {
                        "question_id": v["question_id"], "question": v["question"],
                        "variant": v["variant"], "is_original": v["variant"] == 0,
                        "text": v["text"], "guard": v["guard"],
                        "verdict": verdict.verdict.value,
                        "score": "" if verdict.quality_score is None else verdict.quality_score,
                        "judge_backend": verdict.judge_backend,
                        "judge_model": verdict.judge_model,
                        "paraphrase_model": para.model_label(),
                        "dataset_source": data_source,
                        "latency_ms": round(verdict.latency_ms, 1),
                        "reason": verdict.reason[:250],
                    }
                    log.append("raw", row)
                    rows.append(row)
            print(f"[judge] done in {time.monotonic() - t0:.1f}s")

            # -- per-question consistency -------------------------------------
            per_q: list[dict] = []
            for q in questions:
                qid = q["question_id"]
                grp = [r for r in rows if r["question_id"] == qid]
                resolved = [r for r in grp if r["verdict"] in ("pass", "fail")]
                if len(resolved) < 2:
                    if grp:
                        drop(f"q{qid}:consistency",
                             f"only {len(resolved)} resolved judgements; cannot measure a flip")
                    continue
                scores = [float(r["score"]) for r in resolved]
                verdicts = {r["verdict"] for r in resolved}
                orig = next((r for r in resolved if r["is_original"]), None)
                per_q.append({
                    "question_id": qid,
                    "question": q["question"],
                    "n_variants": len(grp),
                    "n_resolved": len(resolved),
                    "n_error": len(grp) - len(resolved),
                    "flipped": len(verdicts) > 1,
                    "verdict_original": orig["verdict"] if orig else "",
                    "n_pass": sum(1 for r in resolved if r["verdict"] == "pass"),
                    "n_fail": sum(1 for r in resolved if r["verdict"] == "fail"),
                    "score_mean": round(statistics.fmean(scores), 3),
                    "score_sd": round(statistics.pstdev(scores), 3),
                    "score_min": int(min(scores)),
                    "score_max": int(max(scores)),
                    "score_range": int(max(scores) - min(scores)),
                })
            log.write_table("per_question", per_q)

            n_q = len(per_q)
            n_flip = sum(1 for r in per_q if r["flipped"])
            flip_rate = n_flip / n_q if n_q else 0.0
            mean_sd = statistics.fmean([r["score_sd"] for r in per_q]) if n_q else 0.0
            mean_range = statistics.fmean([r["score_range"] for r in per_q]) if n_q else 0.0
            n_wide = sum(1 for r in per_q if r["score_range"] >= 2)
            n_err = sum(1 for r in rows if r["verdict"] == "error")

            # Name the model from a judgement that resolved; an all-ERROR run's first
            # row carries only the requested name, marked as such by the evaluator.
            resolved_rows = [r for r in rows if r["verdict"] in ("pass", "fail")]
            judge_model_used = (resolved_rows or rows or [{"judge_model": ""}])[0]["judge_model"]
            headline = {
                "run_id": log.run_id,
                "judge_backend": judge_backend,
                "judge_model": judge_model_used,
                "paraphrase_model": para.model_label(),
                "answer_source": answer_source,
                "dataset_source": data_source,
                "k_requested": k,
                "n_questions_measured": n_q,
                "n_judgements": len(rows),
                "n_error_judgements": n_err,
                "n_dropped": len(dropped),
                "verdict_flip_rate": round(flip_rate, 4),
                "n_flipped": n_flip,
                "mean_score_sd": round(mean_sd, 3),
                "mean_score_range": round(mean_range, 3),
                "n_score_range_ge_2": n_wide,
            }
            log.write_json("headline", headline)

            print("\n" + "-" * 78)
            print(f"{'qid':>4}  {'n':>2} {'err':>3}  {'flip':>5}  {'pass/fail':>9}  "
                  f"{'mean':>5} {'sd':>5} {'range':>5}  question")
            print("-" * 78)
            for r in per_q:
                print(f"{r['question_id']:>4}  {r['n_resolved']:>2} {r['n_error']:>3}  "
                      f"{'YES' if r['flipped'] else 'no':>5}  "
                      f"{r['n_pass']:>4}/{r['n_fail']:<4}  "
                      f"{r['score_mean']:>5} {r['score_sd']:>5} {r['score_range']:>5}  "
                      f"{r['question'][:34]}")
            print("-" * 78)
            print(f"verdict flip rate      : {flip_rate:.1%}  ({n_flip}/{n_q} answers "
                  f"whose paraphrases were not judged unanimously)")
            print(f"mean score SD          : {mean_sd:.3f} points on a 1-5 scale")
            print(f"mean score range       : {mean_range:.2f}  "
                  f"({n_wide}/{n_q} answers spanned >= 2 points)")
            print(f"ERROR judgements       : {n_err}/{len(rows)}")
            print(f"judge                  : {judge_backend} / {judge_model_used}")
            print(f"paraphraser            : ollama / {para.model_label()}")
            print(f"dataset                : {data_source}")
            print(f"\nresults: {log.dir}")
            return log.dir
        finally:
            judge.close()
            para.close()


def main(argv: Optional[list[str]] = None) -> int:
    p = argparse.ArgumentParser(description="Judge self-consistency under paraphrase")
    p.add_argument("--questions", type=int, default=5)
    p.add_argument("--k", type=int, default=4, help="paraphrases per answer")
    p.add_argument("--judge-backend", choices=("groq", "ollama", "mock"), default="ollama")
    p.add_argument("--judge-model", type=str, default=None)
    p.add_argument("--paraphrase-model", type=str, default=None)
    p.add_argument("--concurrency", type=int, default=4)
    p.add_argument("--pass-threshold", type=int, default=C.PASS_THRESHOLD)
    a = p.parse_args(argv)
    run(n_questions=a.questions, k=a.k, judge_backend=a.judge_backend,
        judge_model=a.judge_model, paraphrase_model=a.paraphrase_model,
        concurrency=a.concurrency, pass_threshold=a.pass_threshold)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
